# Proyecto Final — Arquitecto Cloud
# Sistemas Operativos 750001C | Semestre 1 – 2026

services:
  # Servicio de Frontend (Nginx en Ubuntu 24.04)
  proyecto-docker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: proyecto-docker-frontend-1
    ports:
      - "8080:80"  
    volumes:
      # RUTA GRUPO 1 (Ubuntu/Debian):
      - ./frontend/index.html:/var/www/html/index.html
    restart: unless-stopped
    networks:
      - proyecto-network

  # Servicio de Backend (Python en Ubuntu 24.04)
  proyecto-docker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: proyecto-docker-backend-1
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - proyecto-network

networks:
  proyecto-network:
    driver: bridge
